site_name: biomero-converter
site_url: https://nl-bioimaging.github.io/biomero-converter/
site_description: convert source image to OME-TIFF or OME-Zarr format

repo_name: biomero-converter
repo_url: https://github.com/NL-BioImaging/biomero-converter

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_submodules: true
            show_if_no_docstring: true

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - index.md
  - container.md
  - main.md
  - convert.md
  - overview.md
  - incucyte.md
  - references.md

theme:
  name: material
  color_mode: auto
  user_color_mode_toggle: true
  logo: images/logo.png
