VERSION = '0.1.0'

TILE_SIZE = 1024

TIFF_COMPRESSION = 'LZW'
#TIFF_COMPRESSION = 'JPEGXR_NDPI'
#TIFF_COMPRESSIONARGS = 75

ZARR_CHUNK_SIZE = TILE_SIZE
ZARR_SHARD_MULTIPLIER = 10

PYRAMID_DOWNSCALE = 2
PYRAMID_LEVELS = 6

CONVERSION_ATTEMPTS = 3
