VERSION = 'v0.1.26'

OME_DIR = 'OME'
OME_FILE = 'METADATA.ome.xml'

TILE_SIZE = 1024

TIFF_COMPRESSION = 'LZW'
#TIFF_COMPRESSION = 'JPEGXR_NDPI'
#TIFF_COMPRESSIONARGS = 75

ZARR_CHUNK_SIZE = TILE_SIZE
ZARR_SHARD_MULTIPLIER = 10

PYRAMID_DOWNSCALE = 2
PYRAMID_LEVELS = 6

RETRY_ATTEMPTS = 3
